spring:
  profiles:
    active: local
#  mvc:
#    view:
#      prefix: /WEB-INF/view/
#      suffix: .jsp
#    favicon:
#      enabled: false
#  http:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 1024MB
#  main:
#    banner-mode: log

server:
#  session:
#    timeout: 1
  port: 8088
#session:
#  tomcat:
#    additional-tld-skip-patterns: jaxb-api.jar,jsr173_1.0_api.jar,jaxb1-impl.jar,activation.jar
#          context:
#            JarScanner:
#              scanClassPath: false
#              JarScanFilter:
#                defaultPluggabilityScan: "false"
#          util:
#            scan:
#              StandardJarScanFilter:
#                jarsToSkip: "*"


mybatis:
  mapper-locations: classpath:mybatis/sql/*/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

