logging:
  config: classpath:logback/logback.xml
  
spring:
  datasource:
#   platform: mssql
#   driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#   url: jdbc:log4jdbc:sqlserver://211.41.186.79;databaseName=Tunnel
#   username: sa
#   password: 1
#   dbcp2:
#      test-on-borrow: true
#      validation-query: SELECT 1
   type: com.zaxxer.hikari.HikariDataSource
#   Tunnel_1.0
   url: jdbc:sqlserver://211.41.186.79;databaseName=Tunnel;socketTimeout=10000
   driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
   username: sa
   password: 1
   hikari:
     connection-timeout: 60000
     maximum-pool-size: 5
     connection-test-query: SELECT 1
     idle-timeout: 10000
     minimum-idle: 1
     pool-name: apartDatasourcePool
  devtools:
    livereload:
      enable: true


